### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by stefantaubert** [stefantaubert/cmudict-parser#14]
Conversion failed for `Suckin'--I mean helpin' people an' fightin' an' all that.`

Traceback:

```txt
Traceback (most recent call last):
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/text-utils/text_utils/text.py", line 86, in en_to_ipa_cmu_epitran
    result = CMU_CACHE.sentence_to_ipa(
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/CMUDict.py", line 51, in sentence_to_ipa
    return get_ipa_of_sentence(self._entries_first_ipa, sentence, replace_unknown_with, use_caching)
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 17, in sentence_to_ipa
    ipa_words = [get_ipa_of_word_in_sentence_cache(
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 17, in <listcomp>
    ipa_words = [get_ipa_of_word_in_sentence_cache(
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 30, in get_ipa_of_word_in_sentence_cache
    ipa = get_ipa_of_word_in_sentence(dict, word, replace_unknown_with)
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 38, in get_ipa_of_word_in_sentence
    ipa = get_ipa_of_word_with_punctuation(dict, word, replace_unknown_with)
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 50, in get_ipa_of_word_with_punctuation
    return ipa_of_punctuation_and_words_combined(dict, punctuation_before_word, word_without_punctuation, punctuation_after_word, replace_unknown_with)
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 85, in ipa_of_punctuation_and_words_combined
    ipa_of_word_without_punct = f"{get_ipa_of_words_with_hyphen(dict, word_without_punctuation, replace_unknown_with)}{char_at_end}"
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 107, in get_ipa_of_words_with_hyphen
    ipa = find_combination_of_certain_length_in_dict(
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 119, in find_combination_of_certain_length_in_dict
    word, apos_before, apos_after = strip_apos_at_beginning_and_end_if_they_do_not_belong_to_word(
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 130, in strip_apos_at_beginning_and_end_if_they_do_not_belong_to_word
    word, apos_before = strip_apos(word, 0)
  File "/home/mi/.local/share/virtualenvs/tacotron2-vfc1XCWN/src/cmudict-parser/cmudict_parser/SentenceToIPA.py", line 144, in strip_apos
    while word[pos] == "'":
IndexError: string index out of range
```

**Comment by jasminsternkopf** [comment]
should be working now

**Comment by jasminsternkopf** [comment]
what about this issue?
